spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: 
    initialization-mode: always
    
  jpa:
    hibernate:
      #ddl-auto: validate
      ddl-auto: create